[package]
name = "short_url"
version = "0.1.0"
edition = "2021"
publish = false
  
[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.66"
fastly = "0.8.9"
once_cell = "1.16.0"
rand = "0.8.5"
serde = "1.0.148"
